"""
train_corrector.py
------------------
Train the Learned Latent Denoiser (Corrector network).

Author: Daniel Muskat
Course: CSC 616

Overview:
    The Corrector is a small fully-connected neural network that learns
    to map noisy decoded latent vectors (z_hat) back toward clean latent
    vectors (z). It is trained on the pairs generated by
    generate_training_pairs.py.

    Unlike Hamming or repetition coding — which apply fixed mathematical
    rules designed for generic error channels — the Corrector learns the
    specific statistical structure of errors that JPEG compression produces
    on THIS model's latent space. It exploits correlations between error
    patterns across bit positions that a fixed code cannot.

Architecture:
    Input:  100-dimensional noisy z_hat (Decoder output after JPEG)
    Hidden: 256 → 512 → 256 → 128 units with BatchNorm and LeakyReLU
    Output: 100-dimensional corrected z estimate
    Final:  Tanh activation (matching latent space range [-1, 1])

Training:
    Loss: MSE between corrected output and clean z
    Optimizer: Adam, lr=0.001 with ReduceLROnPlateau scheduler
    Data: Combined QF=75 and QF=30 pairs for generalization
    Epochs: 50 (fast — vectors only, no image processing)

Usage:
    python train_corrector.py

    Run this AFTER generate_training_pairs.py has completed.

Output:
    output/corrector.pth   — trained Corrector model weights

Estimated runtime on M3: 30-90 minutes
"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, ConcatDataset
import time

# ---------------------------------------------------------------------------
# CONFIG
# ---------------------------------------------------------------------------

DATA_DIR = "training_pairs"
SAVE_DIR = "output"
os.makedirs(SAVE_DIR, exist_ok=True)

NZ = 100
HIDDEN_DIMS = [256, 512, 512, 256, 128]
NUM_EPOCHS = 50
BATCH_SIZE = 512
LR = 0.001
VAL_SPLIT = 0.1       # 10% of data held out for validation

device = torch.device("mps" if torch.backends.mps.is_available()
                       else "cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")


# ---------------------------------------------------------------------------
# DATASET
# ---------------------------------------------------------------------------

class LatentPairDataset(Dataset):
    """
    Dataset of (noisy_z_hat, clean_z) pairs.
    Input: noisy z_hat (what the Decoder outputs after JPEG compression)
    Target: clean z (the original latent vector before compression)
    """
    def __init__(self, filepath):
        data = torch.load(filepath, map_location='cpu')
        self.noisy = data["noisy_z_hat"].float()
        self.clean = data["clean_z"].float()
        self.quality = data["jpeg_quality"]
        assert len(self.noisy) == len(self.clean)

    def __len__(self):
        return len(self.noisy)

    def __getitem__(self, idx):
        return self.noisy[idx], self.clean[idx]


# ---------------------------------------------------------------------------
# CORRECTOR NETWORK
# ---------------------------------------------------------------------------

class Corrector(nn.Module):
    """
    Learned Latent Denoiser.

    Maps noisy z_hat → corrected z estimate.

    Design rationale:
    - Fully connected: latent vectors have no spatial structure,
      so convolutions are inappropriate
    - BatchNorm: stabilizes training on the [-1,1] bounded input
    - LeakyReLU: avoids dead neurons in negative region
    - Tanh output: constrains output to [-1,1], matching latent space
    - Residual connection: initialized to learn a small correction
      on top of the identity, which helps early training stability
    """
    def __init__(self, nz=NZ, hidden_dims=HIDDEN_DIMS):
        super().__init__()

        layers = []
        in_dim = nz
        for h_dim in hidden_dims:
            layers.extend([
                nn.Linear(in_dim, h_dim),
                nn.BatchNorm1d(h_dim),
                nn.LeakyReLU(0.2, inplace=True),
            ])
            in_dim = h_dim

        layers.append(nn.Linear(in_dim, nz))
        self.network = nn.Sequential(*layers)
        self.output_activation = nn.Tanh()

    def forward(self, x):
        # Residual connection: learn correction delta, not full mapping
        delta = self.network(x)
        corrected = x + delta * 0.5   # damped residual for stability
        return self.output_activation(corrected)


# ---------------------------------------------------------------------------
# TRAINING
# ---------------------------------------------------------------------------

def evaluate(model, dataloader, criterion):
    model.eval()
    total_loss = 0.0
    total_bit_acc = 0.0
    n_batches = 0

    with torch.no_grad():
        for noisy, clean in dataloader:
            noisy = noisy.to(device)
            clean = clean.to(device)

            corrected = model(noisy)
            loss = criterion(corrected, clean)
            total_loss += loss.item()

            # Bit accuracy: threshold at 0.0
            pred_bits = (corrected > 0.0).float()
            true_bits = (clean > 0.0).float()
            bit_acc = (pred_bits == true_bits).float().mean().item() * 100
            total_bit_acc += bit_acc
            n_batches += 1

    return total_loss / n_batches, total_bit_acc / n_batches


def train():
    print("=" * 65)
    print("Learned Denoiser — Corrector Network Training")
    print("=" * 65)

    # Load datasets
    print("\nLoading training data...")
    datasets = []
    for fname, label in [("pairs_q75.pt", "QF=75"), ("pairs_q30.pt", "QF=30")]:
        fpath = os.path.join(DATA_DIR, fname)
        if os.path.exists(fpath):
            ds = LatentPairDataset(fpath)
            datasets.append(ds)
            print(f"  Loaded {len(ds):,} pairs from {fname} ({label})")
        else:
            print(f"  WARNING: {fpath} not found — skipping")

    if not datasets:
        print("ERROR: No training data found. Run generate_training_pairs.py first.")
        return

    full_dataset = ConcatDataset(datasets)
    total = len(full_dataset)
    val_size = int(total * VAL_SPLIT)
    train_size = total - val_size

    train_dataset, val_dataset = torch.utils.data.random_split(
        full_dataset, [train_size, val_size],
        generator=torch.Generator().manual_seed(42)
    )

    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE,
                              shuffle=True, num_workers=0)
    val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE,
                            shuffle=False, num_workers=0)

    print(f"\n  Training samples:   {train_size:,}")
    print(f"  Validation samples: {val_size:,}")

    # Build model
    model = Corrector(nz=NZ, hidden_dims=HIDDEN_DIMS).to(device)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"\n  Corrector parameters: {n_params:,}")
    print(f"  Hidden dims: {HIDDEN_DIMS}")

    # Loss and optimizer
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=LR)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', factor=0.5, patience=5
    )

    # Training loop
    print(f"\nTraining for {NUM_EPOCHS} epochs...")
    print(f"{'Epoch':>6} {'Train Loss':>12} {'Val Loss':>10} "
          f"{'Val Bit Acc':>12} {'LR':>10} {'Time':>8}")
    print("-" * 65)

    best_val_loss = float('inf')
    best_epoch = 0
    start_time = time.time()

    for epoch in range(1, NUM_EPOCHS + 1):
        epoch_start = time.time()
        model.train()
        train_loss = 0.0
        n_batches = 0

        for noisy, clean in train_loader:
            noisy = noisy.to(device)
            clean = clean.to(device)

            optimizer.zero_grad()
            corrected = model(noisy)
            loss = criterion(corrected, clean)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            train_loss += loss.item()
            n_batches += 1

        avg_train_loss = train_loss / n_batches
        val_loss, val_bit_acc = evaluate(model, val_loader, criterion)
        scheduler.step(val_loss)

        epoch_time = time.time() - epoch_start
        current_lr = optimizer.param_groups[0]['lr']

        print(f"{epoch:>6} {avg_train_loss:>12.6f} {val_loss:>10.6f} "
              f"{val_bit_acc:>11.2f}% {current_lr:>10.6f} {epoch_time:>7.1f}s")

        # Save best model
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_epoch = epoch
            torch.save({
                "model_state_dict": model.state_dict(),
                "epoch": epoch,
                "val_loss": val_loss,
                "val_bit_acc": val_bit_acc,
                "nz": NZ,
                "hidden_dims": HIDDEN_DIMS,
            }, os.path.join(SAVE_DIR, "corrector.pth"))

    total_time = time.time() - start_time
    print("-" * 65)
    print(f"\nTraining complete in {total_time/60:.1f} minutes.")
    print(f"Best model: epoch {best_epoch}, "
          f"val loss {best_val_loss:.6f}, "
          f"saved to {SAVE_DIR}/corrector.pth")

    # Final evaluation summary
    print("\nLoading best model for final evaluation...")
    checkpoint = torch.load(os.path.join(SAVE_DIR, "corrector.pth"),
                            map_location=device)
    model.load_state_dict(checkpoint["model_state_dict"])
    _, final_bit_acc = evaluate(model, val_loader, criterion)
    print(f"Final validation bit accuracy: {final_bit_acc:.2f}%")
    print("\nNext step: run fiveway_compressiontest.py")


if __name__ == "__main__":
    train()
